### ISSUE TITLE
Add a lib for working with dates

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#120]
Currently, standard JS functions are used to calculate dates. The ```date-fns``` lib is also used to format dates.
However, all calculations occur in a not very clear and beautiful way. For example, initializing dates without taking into account the time zone goes like this
``` ts
const date = new Date();
date.setHours(0, 0, 0, 0);
```
Adding a few days to a date looks like this
```ts
date.setDate(date.getDate() + fewDats);
```
Getting the days between dates looks like this
```ts
const millisecondsInDay = 24 * 60 * 60 * 1000;
const diff = (firstDate.getTime() - secondDate.getTime()) / millisecondsInDay;
```

You need to find a library that makes date calculations simpler and more understandable.

**Comment by imblowfish** [comment]
I tried the following list of libraries:
- https://date-fns.org/
- https://day.js.org/
- https://moment.github.io/luxon/#/

And each of these libraries one way or another has its own disadvantage in order to completely migrate all work with dates to them

**date-fns**

We already using it inside `CalculationLogic`'s `getFormattedData` function to get formatted data. It's ok to format data, but I didn't get API to work with i18n from it.

As example https://date-fns.org/v2.30.0/docs/I18n. To change locale and translate date we should change `window.__localeId__` or `global.__localeId__`, but as you can see from MDN doc https://developer.mozilla.org/en-US/docs/Web/API/Window all window's properties are read-only and it's look strange that we should change some property inside object which usually contains read-only properties

**dayjs**

This is too simple library and I tried to implement wrapper around it, because if you need some date without hours you should do something like this:

```ts
dayjs(dayjs().format("YYYY-MM-DD"))
```

Looks a kind of compilcated

Also I found strange behavior in this library, you cannot just add days to data or subtract from it. You should do something like this, because modifiers are pure functions. I don't understand why `copy` function is needed then

```ts
let date = dayjs();
date = date.add(222, "day");
```

It's look ok, but let's show you a more realistic example from our code

```ts
let date = dayjs(dayjs().format("YYYY-MM-DD")).add(15, "day");
...
date = date.subtract(28, "day");
```

Also I found some funny moment

As example:

```ts
function _todayOvulation(countOfCycles: number): Promise<void> {
  let date = dayjs(dayjs().format("YYYY-MM-DD")).add(15, "day");

  const cycles: Cycle[] = [];

  for (let i = 0; i < countOfCycles; ++i) {
    date = date.subtract(28, "day");
    cycles.push({
      cycleLength: 28,
      periodLength: 6,
      startDate: date.toDate().toString(),
    });
  }

  return storage.set.cycles(cycles);
}
```

You can see that I called `date.toDate().toString()`, but why I called it instead of just using `date.toString()`? That's because `date.toString()` returns GMT time by default in case of `toString` usage. However, if we try to log this date with `console.log` it's show us local date. And to get around this oddity we should use `.toDate().toString()`

Additionally `dayjs` has strange plugins system. I tried to extend it with `utc` plugin but it's works only in case of the first call. All next calls throws webpack errors. I still cannot figure out why

![Image](https://github.com/IraSoro/peri/assets/28269602/cc6b93af-477b-4c02-8e3d-21e716997876)
![Image](https://github.com/IraSoro/peri/assets/28269602/b6c5e5ec-bee1-4bf4-bca4-623fff35e390)
![Image](https://github.com/IraSoro/peri/assets/28269602/ff22eca9-8af6-4713-bd2e-549fc3a2861e)

**luxon**

I didn't found any information inside documentation how to work with i18n or any other localization tool. It only provides timezone tools

And also it's look too low level to work with it and we won't get anything special from using it

**Comment by imblowfish** [comment]
@IraSoro please read and if you agree then close ticket or remove milestone. Maybe in the future we'll find another library

**Comment by IraSoro** [comment]
We are already using the ```date-fns``` library for formatting. I looked at it. There are many functions for calculations. I think they suit us. For example, I rewrote this part of the code of the ```getDaysBeforePeriod``` function:
```
  const startDate = cycles[0].startDate;
  const cycleLength = getAverageLengthOfCycle(cycles);

  const dateOfFinish = new Date(startDate);
  dateOfFinish.setHours(0, 0, 0, 0);
  dateOfFinish.setDate(dateOfFinish.getDate() + cycleLength);
  
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  
  const dayBefore = Math.round(
    (Number(dateOfFinish) - Number(now)) / millisecondsInDay,
  );
```
Like this:
```
  const startDate = cycles[0].startDate;
  const cycleLength = getAverageLengthOfCycle(cycles);
  
  const dateOfFinish = new Date(startDate);
  dateOfFinish.setHours(0, 0, 0, 0);
  
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  
  const daysBefore = differenceInDays(addDays(dateOfFinish2, cycleLength), now);
```

Also, we often use the date ```now``` or ```today```. We can move it to global visibility, then the code will become even better:
```
  const startDate = cycles[0].startDate;
  const cycleLength = getAverageLengthOfCycle(cycles);
  
  const dateOfFinish = new Date(startDate);
  dateOfFinish.setHours(0, 0, 0, 0);
  
  const daysBefore = differenceInDays(addDays(dateOfFinish2, cycleLength), today);
```
We can also write our own wrapper function to initialize dates without a time zone. Then everything will be even better. 

I think we can use this library. And rewrite the code a little with it. We can also do this as part of a new task to refactor calculations.
