### ISSUE TITLE
Add Russian language (at least)

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#3]
Add the ability to display the application in Russian.

**Comment by LongJohn-Silver** [comment]
Is it possible to translate it somehow? It looks pretty neat but it makes it almost impossible for some people to use it without their native language support, I'd like to translate it to Spanish, for example.

**Comment by IraSoro** [comment]
Hello @LongJohn-Silver ! Thanks for your interest in this project!
This task requires the use of i18n or any other translation tool. After its completion, it will be easy to add any language.

**Comment by LongJohn-Silver** [comment]
> Hello @LongJohn-Silver ! Thanks for your interest in this project! This task requires the use of i18n or any other translation tool. After its completion, it will be easy to add any language.

You're welcome, this is the best as of now since it's being updated, and it's nice that it also provides a web version, too. drip was nice but I'm unsure if it will still continue to be updated or not, and they seem to not care too much about translating it. 

Let me know if you can add that tool, and I'll gladly translate it to Spanish, which will open the application to be used for a lot of people.

**Comment by gary-host-laptop** [comment]
Hi again, I was wondering if it's possible to translate this into Spanish, or any other language for that matter, because otherwise it prevents a lot of people from using the application unless you speak English.

**Comment by imblowfish** [comment]
> Hi again, I was wondering if it's possible to translate this into Spanish, or any other language for that matter, because otherwise it prevents a lot of people from using the application unless you speak English.

Hello, Spanish will be available started from next release https://github.com/IraSoro/peri/pull/237
