### ISSUE TITLE
Make wrapper

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#79]
Make wrapper around ionic components. It's will help us in case of migration from ionic to another components library and May be useful to split main app logic which now depends on specific ionic's components logic.
As example IonButton will be PeriButton with IonButton inside.

**Comment by imblowfish** [comment]
I understand that this task was proposed to simplify migration from one components library to another, but I found that the problems from wrapper is much more than benefits.

Ionic components is incompatible with other modern components library by API and uses another approaches to work with native and web. Because of this, we have to waste time every time when we'll add a new component to create a universal API to it, Or we'll just leave the same API from Ionic and when introducing a new component library, we will have to change its API 

I think we should keep the current Ionic components and only change them if we move to another framework/library

@IraSoro if you agree with me then could you please close the issue?
